SELECT 
    RH.HISTORY_ID,
    FLOOR(
        C.DAILY_FEE * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1) * 
        (1 - IFNULL(
            (SELECT DP.DISCOUNT_RATE / 100.0
             FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
             WHERE DP.CAR_TYPE = C.CAR_TYPE AND
                   (
                       (DATEDIFF(RH.END_DATE, RH.START_DATE) >= 89 AND DP.DURATION_TYPE = '90일 이상') OR
                       (DATEDIFF(RH.END_DATE, RH.START_DATE) >= 29 AND DATEDIFF(RH.END_DATE, RH.START_DATE) < 89 AND DP.DURATION_TYPE = '30일 이상') OR
                       (DATEDIFF(RH.END_DATE, RH.START_DATE) >= 6 AND DATEDIFF(RH.END_DATE, RH.START_DATE) < 29 AND DP.DURATION_TYPE = '7일 이상')
                   )
             ), 0))
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH ON C.CAR_ID = RH.CAR_ID
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, RH.HISTORY_ID DESC;
